name: Vroom Build

on:
  push:
    branches: [main]
    paths:
      - 'client/**'
  pull_request:
    branches: [main]
    paths:
      - 'client/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y clang libclang-dev libopencv-dev pkg-config cmake llvm
        env:
          LIBCLANG_PATH: /usr/lib/llvm-10/lib

      - name: Install dependencies (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew update
          brew install llvm opencv pkg-config cmake
          echo 'export PATH="/opt/homebrew/opt/llvm/bin:$PATH"' >> $GITHUB_ENV
          echo 'export LDFLAGS="-L/opt/homebrew/opt/llvm/lib"' >> $GITHUB_ENV
          echo 'export CPPFLAGS="-I/opt/homebrew/opt/llvm/include"' >> $GITHUB_ENV
          echo 'export LIBCLANG_PATH="/opt/homebrew/opt/llvm/lib"' >> $GITHUB_ENV
          echo 'export DYLD_LIBRARY_PATH="/opt/homebrew/opt/llvm/lib"' >> $GITHUB_ENV

      - name: Build vroom_client package
        run: cargo build --release --package vroom_client

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: vroom_client-${{ matrix.os }}
          path: target/release/vroom_client

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download artifacts (Linux)
        uses: actions/download-artifact@v3
        with:
          name: vroom_client-ubuntu-latest
          path: artifacts/linux

      - name: Download artifacts (macOS)
        uses: actions/download-artifact@v3
        with:
          name: vroom_client-macos-latest
          path: artifacts/macos

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.0
          release_name: Release v1.0.0
          draft: false
          prerelease: false

      - name: Upload Release Asset (Linux)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/linux/vroom_client
          asset_name: vroom-linux
          asset_content_type: application/octet-stream

      - name: Upload Release Asset (macOS)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/macos/vroom_client
          asset_name: vroom-macos
          asset_content_type: application/octet-stream